-- mlas_constituency_alt.sql  —  adds the alternate/official constituency name (CSV col "dsvgdv").
-- Run any time after mlas_table.sql + mlas_seed.sql.
alter table mlas add column if not exists constituency_alt text;
notify pgrst, 'reload schema';
update mlas set constituency_alt = 'ACHANTA' where candidate_id = '89';
update mlas set constituency_alt = 'ADDANKI' where candidate_id = '91';
update mlas set constituency_alt = 'ADONI' where candidate_id = '83';
update mlas set constituency_alt = 'ALLAGADDA' where candidate_id = '167';
update mlas set constituency_alt = 'ALUR' where candidate_id = '70';
update mlas set constituency_alt = 'AMADALAVALASA' where candidate_id = '86';
update mlas set constituency_alt = 'AMALAPURAM (SC)' where candidate_id = '54';
update mlas set constituency_alt = 'ANAKAPALLE' where candidate_id = '391';
update mlas set constituency_alt = 'ANANTAPUR URBAN' where candidate_id = '184';
update mlas set constituency_alt = 'ANAPARTHY' where candidate_id = '2332';
update mlas set constituency_alt = 'ARAKU VALLEY (ST)' where candidate_id = '171';
update mlas set constituency_alt = 'ATMAKUR' where candidate_id = '172';
update mlas set constituency_alt = 'AVANIGADDA' where candidate_id = '2662';
update mlas set constituency_alt = 'BADVEL (SC)' where candidate_id = '187';
update mlas set constituency_alt = 'BANAGANAPALLE' where candidate_id = '158';
update mlas set constituency_alt = 'BAPATLA' where candidate_id = '59';
update mlas set constituency_alt = 'BHIMAVARAM' where candidate_id = '2098';
update mlas set constituency_alt = 'BHIMILI' where candidate_id = '29';
update mlas set constituency_alt = 'BOBBILI' where candidate_id = '192';
update mlas set constituency_alt = 'CHANDRAGIRI' where candidate_id = '94';
update mlas set constituency_alt = 'CHEEPURUPALLE' where candidate_id = '1089';
update mlas set constituency_alt = 'CHILAKALURIPET' where candidate_id = '312';
update mlas set constituency_alt = 'CHINTALAPUDI (SC)' where candidate_id = '194';
update mlas set constituency_alt = 'CHIRALA' where candidate_id = '197';
update mlas set constituency_alt = 'CHITTOOR' where candidate_id = '34';
update mlas set constituency_alt = 'CHODAVARAM' where candidate_id = '200';
update mlas set constituency_alt = 'DARSI' where candidate_id = '4';
update mlas set constituency_alt = 'DENDULURU' where candidate_id = '201';
update mlas set constituency_alt = 'DHARMAVARAM' where candidate_id = '315';
update mlas set constituency_alt = 'DHONE' where candidate_id = '159';
update mlas set constituency_alt = 'ELURU' where candidate_id = '316';
update mlas set constituency_alt = 'ETCHERLA' where candidate_id = '1033';
update mlas set constituency_alt = 'GAJAPATHINAGARAM' where candidate_id = '97';
update mlas set constituency_alt = 'GAJUWAKA' where candidate_id = '454';
update mlas set constituency_alt = 'GANGADHARA NELLORE (SC)' where candidate_id = '318';
update mlas set constituency_alt = 'GANNAVARAM (KRISHNA)' where candidate_id = '39';
update mlas set constituency_alt = 'GANNAVARAM (SC)' where candidate_id = '2661';
update mlas set constituency_alt = 'GIDDALUR' where candidate_id = '157';
update mlas set constituency_alt = 'GOPALAPURAM (SC)' where candidate_id = '41';
update mlas set constituency_alt = 'GUDIVADA' where candidate_id = '204';
update mlas set constituency_alt = 'GUDUR (SC)' where candidate_id = '236';
update mlas set constituency_alt = 'GUNTAKAL' where candidate_id = '309';
update mlas set constituency_alt = 'GUNTUR EAST' where candidate_id = '287';
update mlas set constituency_alt = 'GUNTUR WEST' where candidate_id = '101';
update mlas set constituency_alt = 'GURAJALA' where candidate_id = '62';
update mlas set constituency_alt = 'HINDUPUR' where candidate_id = '71';
update mlas set constituency_alt = 'ICHCHAPURAM' where candidate_id = '2372';
update mlas set constituency_alt = 'JAGGAMPETA' where candidate_id = '102';
update mlas set constituency_alt = 'JAGGAYYAPETA' where candidate_id = '45';
update mlas set constituency_alt = 'JAMMALAMADUGU' where candidate_id = '2';
update mlas set constituency_alt = 'KADAPA' where candidate_id = '457';
update mlas set constituency_alt = 'KADIRI' where candidate_id = '125';
update mlas set constituency_alt = 'KAIKALUR' where candidate_id = '323';
update mlas set constituency_alt = 'KAKINADA CITY' where candidate_id = '57';
update mlas set constituency_alt = 'KAKINADA RURAL' where candidate_id = '271';
update mlas set constituency_alt = 'KALYANDURG' where candidate_id = '103';
update mlas set constituency_alt = 'KAMALAPURAM' where candidate_id = '325';
update mlas set constituency_alt = 'KANDUKUR' where candidate_id = '367';
update mlas set constituency_alt = 'KANIGIRI' where candidate_id = '326';
update mlas set constituency_alt = 'KAVALI' where candidate_id = '327';
update mlas set constituency_alt = 'KODUMUR (SC)' where candidate_id = '31';
update mlas set constituency_alt = 'KODUR (SC)' where candidate_id = '1358';
update mlas set constituency_alt = 'KONDAPI (SC)' where candidate_id = '328';
update mlas set constituency_alt = 'KOTHAPETA' where candidate_id = '460';
update mlas set constituency_alt = 'KOVUR' where candidate_id = '3';
update mlas set constituency_alt = 'KOVVUR (SC)' where candidate_id = '330';
update mlas set constituency_alt = 'KUPPAM' where candidate_id = '108';
update mlas set constituency_alt = 'KURNOOL' where candidate_id = '357';
update mlas set constituency_alt = 'KURUPAM (ST)' where candidate_id = '334';
update mlas set constituency_alt = 'MACHERLA' where candidate_id = '32';
update mlas set constituency_alt = 'MACHILIPATNAM' where candidate_id = '461';
update mlas set constituency_alt = 'MADAKASIRA (SC)' where candidate_id = '1833';
update mlas set constituency_alt = 'MADANAPALLE' where candidate_id = '23';
update mlas set constituency_alt = 'MADUGULA' where candidate_id = '2677';
update mlas set constituency_alt = 'MANDAPETA' where candidate_id = '261';
update mlas set constituency_alt = 'MANGALAGIRI' where candidate_id = '47';
update mlas set constituency_alt = 'MANTRALAYAM' where candidate_id = '175';
update mlas set constituency_alt = 'MARKAPURAM' where candidate_id = '2647';
update mlas set constituency_alt = 'MUMMIDIVARAM' where candidate_id = '431';
update mlas set constituency_alt = 'MYDUKUR' where candidate_id = '340';
update mlas set constituency_alt = 'MYLAVARAM' where candidate_id = '344';
update mlas set constituency_alt = 'NAGARI' where candidate_id = '121';
update mlas set constituency_alt = 'NANDIGAMA (SC)' where candidate_id = '343';
update mlas set constituency_alt = 'NANDIKOTKUR (SC)' where candidate_id = '358';
update mlas set constituency_alt = 'NANDYAL' where candidate_id = '129';
update mlas set constituency_alt = 'NARASANNAPETA' where candidate_id = '153';
update mlas set constituency_alt = 'NARASARAOPET' where candidate_id = '46';
update mlas set constituency_alt = 'NARASAPURAM' where candidate_id = '408';
update mlas set constituency_alt = 'NARSIPATNAM' where candidate_id = '67';
update mlas set constituency_alt = 'NELLIMARLA' where candidate_id = '398';
update mlas set constituency_alt = 'NELLORE CITY' where candidate_id = '240';
update mlas set constituency_alt = 'NELLORE RURAL' where candidate_id = '11';
update mlas set constituency_alt = 'NIDADAVOLE' where candidate_id = '405';
update mlas set constituency_alt = 'NUZVID' where candidate_id = '355';
update mlas set constituency_alt = 'ONGOLE' where candidate_id = '369';
update mlas set constituency_alt = 'PADERU (ST)' where candidate_id = '142';
update mlas set constituency_alt = 'PALAKOLLU' where candidate_id = '406';
update mlas set constituency_alt = 'PALAKONDA (ST)' where candidate_id = '1059';
update mlas set constituency_alt = 'PALASA' where candidate_id = '130';
update mlas set constituency_alt = 'PALAMANER' where candidate_id = '120';
update mlas set constituency_alt = 'PAMARRU (SC)' where candidate_id = '20';
update mlas set constituency_alt = 'PANYAM' where candidate_id = '60';
update mlas set constituency_alt = 'PARCHUR' where candidate_id = '373';
update mlas set constituency_alt = 'PARVATHIPURAM (SC)' where candidate_id = '137';
update mlas set constituency_alt = 'PATHAPATNAM' where candidate_id = '133';
update mlas set constituency_alt = 'PATTIKONDA' where candidate_id = '126';
update mlas set constituency_alt = 'PAYAKARAOPET (SC)' where candidate_id = '388';
update mlas set constituency_alt = 'PEDANA' where candidate_id = '351';
update mlas set constituency_alt = 'PEDAKURAPADU' where candidate_id = '462';
update mlas set constituency_alt = 'PEDDAPURAM' where candidate_id = '269';
update mlas set constituency_alt = 'PENAMALURU' where candidate_id = '348';
update mlas set constituency_alt = 'PENDURTHI' where candidate_id = '2080';
update mlas set constituency_alt = 'PENUKONDA' where candidate_id = '84';
update mlas set constituency_alt = 'PILERU' where candidate_id = '160';
update mlas set constituency_alt = 'PITHAPURAM' where candidate_id = '272';
update mlas set constituency_alt = 'POLAVARAM (ST)' where candidate_id = '399';
update mlas set constituency_alt = 'PONNUR' where candidate_id = '463';
update mlas set constituency_alt = 'PRATHIPADU' where candidate_id = '464';
update mlas set constituency_alt = 'PRATHIPADU (SC)' where candidate_id = '925';
update mlas set constituency_alt = 'PRODDATUR' where candidate_id = '76';
update mlas set constituency_alt = 'PULIVENDLA' where candidate_id = '178';
update mlas set constituency_alt = 'PUNGANUR' where candidate_id = '440';
update mlas set constituency_alt = 'PUTHALAPATTU (SC)' where candidate_id = '119';
update mlas set constituency_alt = 'RAJAHMUNDRY CITY' where candidate_id = '259';
update mlas set constituency_alt = 'RAJAHMUNDRY RURAL' where candidate_id = '256';
update mlas set constituency_alt = 'RAJAM (SC)' where candidate_id = '135';
update mlas set constituency_alt = 'RAJAMPET' where candidate_id = '21';
update mlas set constituency_alt = 'RAJANAGARAM' where candidate_id = '260';
update mlas set constituency_alt = 'RAMACHANDRAPURAM' where candidate_id = '267';
update mlas set constituency_alt = 'RAMPACHODAVARAM (ST)' where candidate_id = '276';
update mlas set constituency_alt = 'RAPTADU' where candidate_id = '248';
update mlas set constituency_alt = 'RAYACHOTI' where candidate_id = '87';
update mlas set constituency_alt = 'RAYADURG' where candidate_id = '242';
update mlas set constituency_alt = 'RAZOLE (SC)' where candidate_id = '264';
update mlas set constituency_alt = 'REPALLE' where candidate_id = '465';
update mlas set constituency_alt = 'SALUR (ST)' where candidate_id = '138';
update mlas set constituency_alt = 'SANTHANUTHALAPADU (SC)' where candidate_id = '466';
update mlas set constituency_alt = 'SARVEPALLI' where candidate_id = '361';
update mlas set constituency_alt = 'SATTENAPALLE' where candidate_id = '283';
update mlas set constituency_alt = 'SATYAVEDU (SC)' where candidate_id = '444';
update mlas set constituency_alt = 'SINGANAMALA (SC)' where candidate_id = '35';
update mlas set constituency_alt = 'SRIKAKULAM' where candidate_id = '381';
update mlas set constituency_alt = 'SRIKALAHASTI' where candidate_id = '122';
update mlas set constituency_alt = 'SRISAILAM' where candidate_id = '24';
update mlas set constituency_alt = 'SRUNGAVARAPUKOTA' where candidate_id = '467';
update mlas set constituency_alt = 'SULLURPETA (SC)' where candidate_id = '235';
update mlas set constituency_alt = 'TADEPALLIGUDEM' where candidate_id = '409';
update mlas set constituency_alt = 'TADIKONDA (SC)' where candidate_id = '61';
update mlas set constituency_alt = 'TADPATRI' where candidate_id = '58';
update mlas set constituency_alt = 'TANUKU' where candidate_id = '2566';
update mlas set constituency_alt = 'TEKKALI' where candidate_id = '384';
update mlas set constituency_alt = 'TENALI' where candidate_id = '802';
update mlas set constituency_alt = 'THAMBALLAPALLE' where candidate_id = '44';
update mlas set constituency_alt = 'TIRUPATI' where candidate_id = '449';
update mlas set constituency_alt = 'TIRUVURU (SC)' where candidate_id = '342';
update mlas set constituency_alt = 'TUNI' where candidate_id = '254';
update mlas set constituency_alt = 'UDAYAGIRI' where candidate_id = '241';
update mlas set constituency_alt = 'UNDI' where candidate_id = '468';
update mlas set constituency_alt = 'UNGUTURU' where candidate_id = '402';
update mlas set constituency_alt = 'URAVAKONDA' where candidate_id = '14';
update mlas set constituency_alt = 'VEMURU (SC)' where candidate_id = '296';
update mlas set constituency_alt = 'VENKATAGIRI' where candidate_id = '2365';
update mlas set constituency_alt = 'VIJAYAWADA CENTRAL' where candidate_id = '116';
update mlas set constituency_alt = 'VIJAYAWADA EAST' where candidate_id = '88';
update mlas set constituency_alt = 'VIJAYAWADA WEST' where candidate_id = '15';
update mlas set constituency_alt = 'VINUKONDA' where candidate_id = '64';
update mlas set constituency_alt = 'VISAKHAPATNAM EAST' where candidate_id = '114';
update mlas set constituency_alt = 'VISAKHAPATNAM NORTH' where candidate_id = '2684';
update mlas set constituency_alt = 'VISAKHAPATNAM SOUTH' where candidate_id = '2262';
update mlas set constituency_alt = 'VISAKHAPATNAM WEST' where candidate_id = '469';
update mlas set constituency_alt = 'VIZIANAGARAM' where candidate_id = '470';
update mlas set constituency_alt = 'YELAMANCHILI' where candidate_id = '211';
update mlas set constituency_alt = 'YEMMIGANUR' where candidate_id = '163';
update mlas set constituency_alt = 'YERRAGONDAPALEM (SC)' where candidate_id = '162';
