-- ============================================================
--  scheme_hod_mapping.sql
--  GoI Funds: move the Department / HoD off the fund tables into
--  their own normalised mapping table (mirrors gsdp_mapping).
--    * New table scheme_hod_mapping(css_name, state_scheme, department, hod):
--        - a scheme is identified by css_name (+ state_scheme);
--        - one scheme mapped to several HoDs  = several rows;
--        - a row with a BLANK/NULL state_scheme is a wildcard for every
--          state-scheme under that css_name.
--    * SEED it from the existing goi_funds_live / goi_funds_district_live
--      department & hod columns (so current mappings are preserved).
--    * THEN drop those columns from the two fund tables.
--  The dashboard joins the fund rows to this table (by css_name [+ state_scheme])
--  to decide which Department / HoD a scheme belongs to.
--  Order matters: create -> seed -> drop.  Safe to re-run.
-- ============================================================

-- 1) The new normalised mapping table (create FIRST, before dropping columns).
--    id is GENERATED BY DEFAULT (not ALWAYS) so a bulk CSV/SQL import that
--    includes an "id" column still works; Postgres auto-fills it when omitted.
create table if not exists scheme_hod_mapping (
  id           bigint generated by default as identity primary key,
  css_name     text not null,
  state_scheme text,
  department   text,
  hod          text,
  updated_at   timestamptz default now()
);
-- If the table already exists with GENERATED ALWAYS, relax it (safe to re-run):
alter table scheme_hod_mapping alter column id set generated by default;

create index if not exists scheme_hod_mapping_css_idx   on scheme_hod_mapping (css_name);
create index if not exists scheme_hod_mapping_state_idx on scheme_hod_mapping (state_scheme);
create index if not exists scheme_hod_mapping_hod_idx   on scheme_hod_mapping (hod);
create index if not exists scheme_hod_mapping_dept_idx  on scheme_hod_mapping (department);

-- 2) The dashboard / admin (anon key) reads & rewrites this table.
alter table scheme_hod_mapping disable row level security;
grant select, insert, update, delete on scheme_hod_mapping to anon, authenticated;

-- 3) SEED from the existing dept/hod columns on the fund tables.
--    Guarded by a column-existence check so it only runs while those columns
--    still exist (i.e. the first time), and is therefore safe to re-run.
--    Only inserts rows that aren't already present (so re-running won't duplicate).
do $$
begin
  if exists (select 1 from information_schema.columns
             where table_schema = 'public' and table_name = 'goi_funds_live'
               and column_name = 'department') then
    insert into scheme_hod_mapping (css_name, state_scheme, department, hod)
    select distinct s.css_name, s.state_scheme, s.department, s.hod
    from goi_funds_live s
    where (coalesce(s.department,'') <> '' or coalesce(s.hod,'') <> '')
      and not exists (
        select 1 from scheme_hod_mapping m
        where m.css_name = s.css_name
          and coalesce(m.state_scheme,'') = coalesce(s.state_scheme,'')
          and coalesce(m.department,'')   = coalesce(s.department,'')
          and coalesce(m.hod,'')          = coalesce(s.hod,'')
      );
  end if;

  if exists (select 1 from information_schema.columns
             where table_schema = 'public' and table_name = 'goi_funds_district_live'
               and column_name = 'department') then
    insert into scheme_hod_mapping (css_name, state_scheme, department, hod)
    select distinct s.css_name, s.state_scheme, s.department, s.hod
    from goi_funds_district_live s
    where (coalesce(s.department,'') <> '' or coalesce(s.hod,'') <> '')
      and not exists (
        select 1 from scheme_hod_mapping m
        where m.css_name = s.css_name
          and coalesce(m.state_scheme,'') = coalesce(s.state_scheme,'')
          and coalesce(m.department,'')   = coalesce(s.department,'')
          and coalesce(m.hod,'')          = coalesce(s.hod,'')
      );
  end if;
end $$;

-- 4) NOW drop the dept/hod columns from the two fund tables.
alter table goi_funds_live          drop column if exists department;
alter table goi_funds_live          drop column if exists hod;
alter table goi_funds_district_live drop column if exists department;
alter table goi_funds_district_live drop column if exists hod;

notify pgrst, 'reload schema';
